
# Sample template

Resources: {
 myEC2Instance: {
 Type: "AWS::EC2::Instance",
 Properties: {
 :
 IamInstanceProfile: { Ref: "RootInstanceProfile" },
 :
 }
 },
  RootRole: {
 Type: "AWS::IAM::Role",
 Properties: {
 AssumeRolePolicyDocument: {
 Statement: [{
 Effect: "Allow",
 Principal: { Service: ["ec2.amazonaws.com" ] },
 Action: [ "sts:AssumeRole" ]
 }]},
 Path: "/"
 }
 },
 RolePolicy: {
 Type: "AWS::IAM::Policy",
 Properties: {
 PolicyName: "root",
 PolicyDocument: {
 Statement: [{
 Effect: "Allow",
 Action: "cloudformation:DescribeStackResource",
 Resource: "*"
 }]},
 Roles: [{ Ref: "RootRole" }]
 }
 },
 RootInstanceProfile: {
 Type: "AWS::IAM::InstanceProfile",
 Properties: {
 Path: "/",
 Roles: [{ Ref: "RootRole" }]
 }
 }
:
}